apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-gloo
  namespace: {{ .Release.Namespace }}
  labels:
    gloo: control-plane
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.gloo.type }}
  ports:
    - port: {{ .Values.gloo.port }}
      protocol: TCP
      name: http
  selector:
    gloo: control-plane
    release: {{ .Release.Name }}