---
#rbac for gloo-discovery
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-discovery-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["gloo.solo.io"]
  resources: ["upstreams", "virtualhosts"]
  verbs: ["*"]