apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "ingress.fullname" . }} 
  namespace: {{ .Release.Namespace }}
  labels:
    gloo: ingress
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.ingress.replicaCount }}
  selector:
    matchLabels:
      gloo: ingress
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        gloo: ingress
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: assignnodeid
        image: busybox
        command:
        - sed
        - s/NODE_ID_PLACE_HOLDER/$(POD_NAME).$(POD_NAMESPACE)/
        - -i
        - "/config/envoy.yaml"
        volumeMounts:
        - name: envoy-config
          mountPath: /config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
      containers:
      - name: envoy
        image: "{{ .Values.ingress.image }}:{{ .Values.ingress.imageTag }}"
        imagePullPolicy: {{ .Values.ingress.imagePullPolicy }}
        ports: 
        - containerPort: {{ .Values.ingress.port }}
          name: http
        - containerPort: {{ .Values.ingress.securePort }} 
          name: https
        - containerPort: {{ .Values.ingress.adminPort }}
          name: admin
        command: ["envoy"]
        args: ["-c", "/config/envoy.yaml", "--v2-config-only"]
        volumeMounts:
        - name: envoy-config
          mountPath: /config
      volumes:
      - name: envoy-config
        configMap:
          name: {{ template "ingress.fullname" .}}-config 