{{ if .Values.opentracing.status -}}
{{ if eq .Values.opentracing.status "install" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jaeger.name" . }}
  labels:
    sevice: jaeger
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 9411
    protocol: TCP
    name: tracing
  - port: 16686
    protocol: TCP
    name: web
  selector:
    app: jaeger
  type: NodePort
{{ end -}}
{{ end -}}