# TODO: remove this when we move istio importer to separate repo
[[override]]
  name = "github.com/golang/protobuf"
  revision = "1e59b77b52bf8e4b449a57e6f79f21226d571845"

[[constraint]]
  branch = "master"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "0.5.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.7.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"
