#---
#system namespace
apiVersion: v1
kind: Namespace
metadata:
  name: gloo-system
---
# statsd-grafana deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: statsd-grafana
  name: statsd-grafana
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: statsd-grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: statsd-grafana
    spec:
      containers:
      - image: kamon/grafana_graphite:latest
        name: statsd-grafana
        ports:
        - containerPort: 80
          name: grafana-web
        - containerPort: 81
          name: graphite-web
        - containerPort: 2003
          name: graphite-data
        - containerPort: 8125
          name: statsd
        - containerPort: 8126
          name: statsd-admin
---
# statsd-grafana service
apiVersion: v1
kind: Service
metadata:
  name: statsd-grafana
  labels:
    sevice: statsd-grafana
  namespace: gloo-system
spec:
  ports:
  - port: 80
    protocol: TCP
    name: grafana-web
  - port: 81
    name: graphite-web
    protocol: TCP
  - port: 2003
    protocol: TCP
    name: graphite-data
  - port: 8125
    protocol: TCP
    name: statsd
  - port: 8126
    protocol: TCP
    name: statsd-admin
  selector:
    app: statsd-grafana
  type: NodePort
---
# jaeger deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jaeger
  name: jaeger
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: jaeger
  replicas: 1
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - image: jaegertracing/all-in-one:latest
        env:
        - name: COLLECTOR_ZIPKIN_HTTP_PORT
          value: "9411"
        name: jaeger
        ports:
        - containerPort: 9411
          name: tracing
        - containerPort: 16686
          name: web
---
# jaeger service
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    sevice: jaeger
  namespace: gloo-system
spec:
  ports:
  - port: 9411
    protocol: TCP
    name: tracing
  - port: 16686
    protocol: TCP
    name: web
  selector:
    app: jaeger
  type: NodePort
---
# gloo pods
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gloo
  name: gloo
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: gloo
  replicas: 1
  template:
    metadata:
      labels:
        app: gloo
    spec:
      containers:
      - image: solo-io/gloo:v0.1
        imagePullPolicy: Never
        name: gloo
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        command: ["/gloo"]
        args:
        - "--storage.type=kube"
        - "--storage.refreshrate=30m"
        - "--secrets.type=kube"
        - "--secrets.refreshrate=30m"
        - "--xds.port=8081"
        - "--kube.namespace=gloo-system"
---
# gloo service
apiVersion: v1
kind: Service
metadata:
  name: gloo
  labels:
    sevice: gloo
  namespace: gloo-system
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: gloo
---
apiVersion: v1
data:
  envoy.yaml: |
    node:
      cluster: ingress
      id: ingress

    static_resources:
      clusters:
      - name: xds_cluster
        connect_timeout: 5.000s
        hosts:
        - socket_address:
            address: gloo
            port_value: 8081
        http2_protocol_options: {}
        type: STRICT_DNS
      - name: jaeger
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: jaeger
            port_value: 9411
      - name: statsd
        connect_timeout: 1s
        type: strict_dns
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: statsd-grafana
            port_value: 8025

    dynamic_resources:
      ads_config:
        api_type: GRPC
        cluster_names:
        - xds_cluster
      cds_config:
        ads: {}
      lds_config:
        ads: {}

    stats_sinks:
    - name: envoy.statsd
      config:
        tcp_cluster_name: statsd

    tracing:
      http:
        name: envoy.zipkin
        config:
          collector_cluster: jaeger
          collector_endpoint: "/api/v1/spans"

    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19000
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: gloo-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: envoy
  name: envoy
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      app: envoy
  replicas: 1
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - image: docker.io/envoyproxy/envoy-alpine:latest
        name: envoy
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8443
          name: https
        - containerPort: 19000
          name: admin
        command: ["envoy"]
        args: ["-c", "/config/envoy.yaml", "--v2-config-only", "--service-cluster", "envoy", "--service-node", "envoy"]
        volumeMounts:
        - name: envoy-config
          mountPath: /config
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    sevice: envoy
  namespace: gloo-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 8443
    protocol: TCP
    name: https
  - port: 19000
    protocol: TCP
    name: admin
  selector:
    app: envoy