apiVersion: v1
data:
  envoy.yaml: |
    node:
      cluster: ingress
      id: test
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 19000
    dynamic_resources:
      ads_config:
        api_type: GRPC
        cluster_names:
        - xds_cluster
      cds_config:
        ads: {}
      lds_config:
        ads: {}
    static_resources:
      clusters:
      - connect_timeout: 5.000s
        hosts:
        - socket_address:
            address: gloo
            port_value: 8081
        http2_protocol_options: {}
        name: xds_cluster
        type: STRICT_DNS
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: gloo-system