apiVersion: v1
kind: Service
metadata:
  name: envoy
  labels:
    sevice: envoy
  namespace: gloo-system
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: http
  - port: 8443
    protocol: TCP
    name: https
  - port: 9901
    protocol: TCP
    name: admin
  selector:
    app: envoy
  # nodeport for manual debugging
  type: NodePort