apiVersion: v1
kind: Service
metadata:
  name: upstream-for-events
  labels:
    sevice: upstream-for-events
  namespace: gloo-system
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: upstream-for-events