apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: upstream-for-events
  name: upstream-for-events
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: upstream-for-events
  replicas: 1
  template:
    metadata:
      labels:
        gloo: upstream-for-events
    spec:
      containers:
      - image: soloio/upstream-for-events:testing
        imagePullPolicy: Always
        name: upstream-for-events
        ports:
        - containerPort: 8080
          name: http