apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: ingress-controller
  name: ingress-controller
  namespace: gloo-system
spec:
  selector:
    matchLabels:
      gloo: ingress-controller
  replicas: 1
  template:
    metadata:
      labels:
        gloo: ingress-controller
    spec:
      containers:
      - image: soloio/ingress-controller:v0.1
        name: ingress-controller
        env:
        - name: DEBUG
          value: "1"
        - name: GRPC_TRACE
          value: all
        command: ["/ingress-controller"]
        args:
        - "--service=envoy"
        - "--syncperiod=30m"
        - "--storage.type=kube"
        - "--kube.namespace=gloo-system"
