{{ if .Values.kube-upstream-discovery.enable }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    gloo: kube-upstream-discovery
  name: {{ .Release.Name }}-service-discovery
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      gloo: kube-upstream-discovery
  replicas: 1
  template:
    metadata:
      labels:
        gloo: kube-upstream-discovery
    spec:
      containers:
      - image: {{ .Values.kube-upstream-discovery.image }}:{{ .Values.kube-upstream-discovery.imageTag }}
        imagePullPolicy: {{ .Values.kube-upstream-discovery.imagePullPolicy }}
        name: kube-upstream-discovery
        env:
        - name: GRPC_TRACE
          value: "all"
        - name: DEBUG
          value: "1"
        args:
        - "--storage.type=kube"
        - "--syncperiod=30m"
        - "--kube.namespace={{ .Release.Namespace }}"
{{ end }}