- example_rule:
    timeout: 15s
    match:
      prefix: /Desktop
    upstream:
      name: foo_service
      address: 127.0.0.1
      port: 1234
- example_rule:
    timeout: 5s
    match:
      prefix: /Downloads
    upstream:
      name: bar_service
      address: 127.0.0.1
      port: 3456
